if __name__=='__main__':

    search_terms = ['python data engineer']
    dataset_name ='tweets'

    # search last day
    from datetime import datetime, timedelta, timezone
    
    last_midnight = datetime.now(timezone.utc).replace(hour=0, minute=0, second=0, microsecond=0) 
    data_interval_start = last_midnight - timedelta(days=1)
    data_interval_end = last_midnight

    start_time = data_interval_start.isoformat()
    end_time = data_interval_end.isoformat()

    pipeline = dlt.pipeline(pipeline_name='twitter', destination='bigquery', dataset_name='twitter_data')

    # run the pipeline with your parameters and print the outcome
    load_info = pipeline.run(twitter_source(search_terms=search_terms, start_time=start_time, end_time=end_time))

    print(load_info)
